from __future__ import annotations

from pathlib import Path

from helixaccel.storage.run_record import RunRecord


def _fmt(value: object) -> str:
    if value is None:
        return "-"
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def render_markdown_report(record: RunRecord) -> str:
    profile = record.dataset_profile
    sorted_steps = sorted(record.steps, key=lambda step: step["runtime_sec"], reverse=True)
    top = sorted_steps[:3]

    lines: list[str] = []
    lines.append(f"# HelixAccel Benchmark Report — {record.run_id}")
    lines.append("")
    lines.append(f"Dataset: `{record.dataset}`")
    lines.append(f"Backend: `{record.backend}`")
    lines.append(f"Pipeline: `{record.pipeline}`")
    lines.append(f"Success: `{record.success}`")
    lines.append(f"Total runtime: `{record.total_runtime_sec:.3f} sec`")
    lines.append("")

    lines.append("## Dataset profile")
    lines.append("")
    lines.append(f"- Cells: `{profile.get('n_cells')}`")
    lines.append(f"- Genes: `{profile.get('n_genes')}`")
    lines.append(f"- NNZ: `{profile.get('nnz')}`")
    lines.append(f"- Sparsity: `{profile.get('sparsity')}`")
    lines.append(f"- Matrix format: `{profile.get('matrix_format')}`")
    lines.append(f"- Dense estimate GB: `{profile.get('estimated_dense_gb')}`")
    lines.append(f"- Sparse estimate GB: `{profile.get('estimated_sparse_gb')}`")
    lines.append("")

    lines.append("## Runtime by step")
    lines.append("")
    lines.append("| Step | Runtime sec | Peak RAM MB | Matrix before | Matrix after | Success |")
    lines.append("|---|---:|---:|---|---|---|")
    for step in record.steps:
        before = step["matrix_before"]
        after = step["matrix_after"]
        lines.append(
            "| {name} | {runtime} | {ram} | {before_fmt} {before_shape} | {after_fmt} {after_shape} | {success} |".format(
                name=step["name"],
                runtime=_fmt(step["runtime_sec"]),
                ram=_fmt(step["peak_rss_mb"]),
                before_fmt=before.get("matrix_format"),
                before_shape=before.get("shape"),
                after_fmt=after.get("matrix_format"),
                after_shape=after.get("shape"),
                success=step["success"],
            )
        )
    lines.append("")

    lines.append("## Bottleneck summary")
    lines.append("")
    for idx, step in enumerate(top, start=1):
        lines.append(f"{idx}. `{step['name']}` — `{step['runtime_sec']:.3f} sec`")
    lines.append("")

    lines.append("## Memory observations")
    lines.append("")
    max_mem_step = max(record.steps, key=lambda step: step["peak_rss_mb"], default=None)
    if max_mem_step:
        lines.append(
            f"Highest sampled RAM: `{max_mem_step['peak_rss_mb']:.3f} MB` during `{max_mem_step['name']}`."
        )
    else:
        lines.append("No step memory data available.")
    lines.append("")

    lines.append("## Phase 1 note")
    lines.append("")
    lines.append(
        "This report is generated by the Phase 1 CPU benchmark skeleton. "
        "GPU execution, biological validation gates, cost model, and planner v0 are intentionally out of scope here."
    )
    lines.append("")
    return "\n".join(lines)


def save_markdown_report(record: RunRecord, reports_dir: Path) -> Path:
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"{record.run_id}.md"
    path.write_text(render_markdown_report(record), encoding="utf-8")
    return path
